version: '3.4'

services:
  api-server:
    image: ${DOCKER_REGISTRY-}grpcserver
    build:
      context: .
      dockerfile: api-server/Dockerfile

  dapr-grpc-client:
    image: ${DOCKER_REGISTRY-}daprgrpcclient
    build:
      context: .
      dockerfile: dapr-grpc-client/Dockerfile
    depends_on:
      - api-server

networks:
    dapr-grpc: