version: '3.4'

services:
  grpc-server:
    image: ${DOCKER_REGISTRY-}grpcserver
    build:
      context: .
      dockerfile: grpc-server/Dockerfile

  dapr-grpc-client:
    image: ${DOCKER_REGISTRY-}daprgrpcclient
    build:
      context: .
      dockerfile: dapr-grpc-client/Dockerfile
    depends_on:
      - grpc-server

networks:
    dapr-grpc: