version: '3.4'

services:
  grpc-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    ports:
    #  - "6001:443"
      - "6001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - dapr-grpc
  dapr-grpc-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    ports:
      - "6002:80"
    networks:
      - dapr-grpc

  grpc-server-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
     "-app-id", "grpc-server",
     "-app-port", "80",
     #"-app-protocol","grpc",
     #"-dapr-grpc-port", "3500",
     #"-placement-host-address", "placement:50006" # Dapr's placement service can be reach via the docker DNS entry
     ]
    #volumes:
    #    - "./components/:/components" # Mount our components folder for the runtime to use
    depends_on:
      - grpc-server
    network_mode: "service:grpc-server" # Attach the nodeapp-dapr service to the nodeapp network namespace

  dapr-grpc-client-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd", "-app-id", "dapr-grpc-client", "-app-port", "80", 
          #"-app-protocol","grpc",
    #"-dapr-grpc-port", "3500", 
    #"-placement-host-address", "placement:50006"
    ]
    depends_on:
      - dapr-grpc-client
    network_mode: "service:dapr-grpc-client"

  #placement:
  #  image: "daprio/dapr"
  #  command: ["./placement", "-port", "50006"]
  #  ports:
  #    - "50006:50006"
  #  networks:
  #    - dapr-grpc